openapi: "3.0.0"
info:
  version: 1.0.0
  title: My app
servers:
  - url: http://xxxxxxx
# security:
tags: 
  - name: Users
    description: Users operations
paths:
  /users:
    get:
      summary: List all users
      operationId: listUsers
      tags:
        - Users
      parameters:
        - name: limit
          in: query
          required: false
          schema:
            type: integer
        - name: offset
          in: query
          required: false
          schema:
            type: integer
      responses:
        200:
          description: A list of users
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Users"
        500:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
    post:
      summary: Create a user
      operationId: createUser
      tags:
        - Users
      responses:
        201:
          description: A new user
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        500:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
  /users/{userId}:
    get:
      summary: A specific user
      operationId: showUser
      tags:
        - Users
      parameters:
        - name: userId
          in: path
          required: true
          description: The id of the user to retrieve
          schema:
            type: string
      responses:
        200:
          description: Expected response to a valid request
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        500:
          description: unexpected error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Error"
      
components:
  schemas:
    Users:
      properties:
        metadata:
          properties:
            offset:
              type: integer
            limit:
              type: integer
            total: 
              type: integer
        data:
          type: array
          items:
            $ref: "#/components/schemas/User"
    User:
      properties:
        id:
          type: string
          format: uuid
        createdAt:
          type: string
          format: date-time
        updatedAt:
          type: string
          format: date-time
        name:
          type: string        
    Error:
      properties:
        statusCode:
          type: integer
          format: int32
        error:
          type: string
        message:
          type: string