version: 2
machine:
  environment:
      MOCHA_FILE: "$CIRCLE_TEST_REPORTS/test-results/mocha/results.xml"
jobs:
  build:
    docker:
      - image: circleci/node:10.15.0
      - image: circleci/postgres:9.6-alpine
        environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345678
          POSTGRES_DB: my_app
    working_directory: ~/repo
    steps:
      - checkout
      - run:
          name: npm-install
          command: npm install
      - run: mkdir ~/test-results      
      - run:
          command: 'node_modules/.bin/mocha --reporter mocha-junit-reporter --reporter-options mochaFile=~/test-results/mocha/results.xml'
      - store_test_results:
          path: ~/test-results/mocha/results.xml
      - store_artifacts:
          path: ~/test-results/mocha/results.xml
